# TruffleHog configuration file
# https://github.com/trufflesecurity/trufflehog

# Global configuration
chunk_size: 10240
concurrency: 10
detector_timeout: 10s
verify_timeout: 30s

# Only scan verified secrets (reduces false positives)
only_verified: true

# Detectors to include (leave empty to include all)
detectors:
  # Common cloud providers
  - aws
  - azure
  - gcp
  - digitalocean
  
  # Database services
  - mongodb
  - mysql
  - postgres
  - redis
  
  # API services
  - github
  - gitlab
  - slack
  - discord
  - telegram
  
  # CI/CD and deployment
  - dockerhub
  - heroku
  - netlify
  - vercel
  
  # Payment and analytics
  - stripe
  - paypal
  - googleanalytics
  
  # Email services
  - sendgrid
  - mailgun
  - postmark

# Paths to exclude from scanning
exclude_paths:
  - "**/.git/**"
  - "**/node_modules/**"
  - "**/venv/**"
  - "**/env/**"
  - "**/.venv/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/htmlcov/**"
  - "**/coverage.xml"
  - "**/.coverage"
  - "**/pytest_cache/**"
  - "**/.pytest_cache/**"
  - "**/docs/_build/**"
  - "**/.tox/**"
  - "**/.mypy_cache/**"
  - "**/src/puffinflow/version.py"  # Generated file
  - "**/.security-scan-marker"      # Our dummy file

# File extensions to exclude
exclude_extensions:
  - ".log"
  - ".tmp"
  - ".cache"
  - ".lock"
  - ".egg-info"

# Custom regex patterns to exclude (reduce false positives)
exclude_detectors:
  # Exclude common test patterns that might look like secrets
  - name: "test-patterns"
    regex: 
      - "test[_-]?key"
      - "dummy[_-]?secret"
      - "fake[_-]?token"
      - "example[_-]?api[_-]?key"
      - "placeholder[_-]?password"

# Custom allowlist for known false positives
allowlist:
  paths:
    - "tests/**"  # Test files often contain dummy secrets
    - "examples/**"  # Example files may contain placeholder secrets
    - "docs/**"   # Documentation may contain example secrets
  
  # Specific strings that are known to be safe
  regexes:
    - "your\\.email@example\\.com"  # Placeholder email in pyproject.toml
    - "yourusername"  # Placeholder username in URLs
    - "github\\.com/yourusername"  # Placeholder GitHub URLs

# Output configuration
output:
  format: "json"
  file: "trufflehog-results.json"

# Logging configuration
log:
  level: "info"
  format: "text"

# GitHub Actions specific configuration
github_actions: true

# Fail on verified secrets found
fail: true

# Skip files larger than 10MB
max_file_size: 10485760

# Additional performance settings
no_verification: false
archive_max_size: 20971520
archive_max_depth: 5