name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  trufflehog-scan:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full git history

      - name: Verify git history
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Total commits: $(git rev-list --count HEAD)"
          echo "Latest commit: $(git log -1 --oneline)"
          
          # Check if we have enough commits for comparison
          COMMIT_COUNT=$(git rev-list --count HEAD)
          if [ "$COMMIT_COUNT" -lt 2 ]; then
            echo "Warning: Only $COMMIT_COUNT commit(s) found. TruffleHog needs at least 2 commits for comparison."
            echo "Creating a dummy commit to enable scanning..."
            
            # Configure git for the action
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            
            # Create a dummy file and commit if needed
            echo "# Security Scan Marker" > .security-scan-marker
            git add .security-scan-marker
            git commit -m "Add security scan marker for TruffleHog"
            
            echo "New commit count: $(git rev-list --count HEAD)"
          fi

      - name: Run TruffleHog scan (Full Repository)
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --debug --only-verified --json --no-update

      - name: Run TruffleHog scan (Differential)
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.before || 'HEAD~1' }}
          head: ${{ github.sha }}
          extra_args: --debug --only-verified --json --no-update

      - name: Run TruffleHog scan (Fallback - Full scan if differential fails)
        if: failure() && (github.event_name == 'push' || github.event_name == 'pull_request')
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --debug --only-verified --json --no-update

  additional-security-checks:
    name: Additional Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety semgrep

      - name: Run Bandit security linter
        run: |
          bandit -r src/ -f json -o bandit-report.json
          bandit -r src/ -f txt

      - name: Run Safety check for known vulnerabilities
        run: |
          safety check --json --output safety-report.json || true
          safety check

      - name: Run Semgrep security analysis
        run: |
          semgrep --config=auto src/ --json --output=semgrep-report.json || true
          semgrep --config=auto src/

      - name: Upload security reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json
            semgrep-report.json

  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [trufflehog-scan, additional-security-checks]
    if: always()
    steps:
      - name: Security Scan Summary
        run: |
          echo "## Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.trufflehog-scan.result }}" == "success" ]; then
            echo "✅ **TruffleHog Secret Scan**: Passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **TruffleHog Secret Scan**: Failed or found issues" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.additional-security-checks.result }}" == "success" ]; then
            echo "✅ **Additional Security Checks**: Passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Additional Security Checks**: Failed or found issues" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Recommendations" >> $GITHUB_STEP_SUMMARY
          echo "- Review any flagged secrets or security issues" >> $GITHUB_STEP_SUMMARY
          echo "- Update dependencies with known vulnerabilities" >> $GITHUB_STEP_SUMMARY
          echo "- Follow security best practices for code development" >> $GITHUB_STEP_SUMMARY